//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMA.APZRPMJ2018.WalletSimulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KMA.APZRPMJ2018.WalletSimulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get user.{0}Reason: {1}.
        /// </summary>
        internal static string SignIn_FailedToGetUser {
            get {
                return ResourceManager.GetString("SignIn_FailedToGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate password.{0}Reason: {1}.
        /// </summary>
        internal static string SignIn_FailedToValidatePassword {
            get {
                return ResourceManager.GetString("SignIn_FailedToValidatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with login {0} doesn&apos;t exist!.
        /// </summary>
        internal static string SignIn_UserDoesntExist {
            get {
                return ResourceManager.GetString("SignIn_UserDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password!.
        /// </summary>
        internal static string SignIn_WrongPassword {
            get {
                return ResourceManager.GetString("SignIn_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address {0} is not valid!.
        /// </summary>
        internal static string SignUp_EmailIsNotValid {
            get {
                return ResourceManager.GetString("SignUp_EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create user.{0}Reason: {1}.
        /// </summary>
        internal static string SignUp_FailedToCreateUser {
            get {
                return ResourceManager.GetString("SignUp_FailedToCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to validate data.{0}Reason: {1}.
        /// </summary>
        internal static string SignUp_FailedToValidateData {
            get {
                return ResourceManager.GetString("SignUp_FailedToValidateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with login {0} already exists!.
        /// </summary>
        internal static string SignUp_UserAlreadyExists {
            get {
                return ResourceManager.GetString("SignUp_UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with login {0} doesn&apos;t exist!.
        /// </summary>
        internal static string SignUp_UserdoesntExist {
            get {
                return ResourceManager.GetString("SignUp_UserdoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} successfully created!.
        /// </summary>
        internal static string SignUp_UserSuccessfulyCreated {
            get {
                return ResourceManager.GetString("SignUp_UserSuccessfulyCreated", resourceCulture);
            }
        }
    }
}
